# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_swagger_api
from eve_swagger_api.models.put_fleets_fleet_id_squads_squad_id_naming import PutFleetsFleetIdSquadsSquadIdNaming  # noqa: E501
from eve_swagger_api.rest import ApiException


class TestPutFleetsFleetIdSquadsSquadIdNaming(unittest.TestCase):
    """PutFleetsFleetIdSquadsSquadIdNaming unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutFleetsFleetIdSquadsSquadIdNaming(self):
        """Test PutFleetsFleetIdSquadsSquadIdNaming"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_swagger_api.models.put_fleets_fleet_id_squads_squad_id_naming.PutFleetsFleetIdSquadsSquadIdNaming()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
