# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    OpenAPI spec version: 1.19
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import eve_swagger_api
from eve_swagger_api.models.put_fleets_fleet_id_wings_wing_id_not_found import PutFleetsFleetIdWingsWingIdNotFound  # noqa: E501
from eve_swagger_api.rest import ApiException


class TestPutFleetsFleetIdWingsWingIdNotFound(unittest.TestCase):
    """PutFleetsFleetIdWingsWingIdNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutFleetsFleetIdWingsWingIdNotFound(self):
        """Test PutFleetsFleetIdWingsWingIdNotFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = eve_swagger_api.models.put_fleets_fleet_id_wings_wing_id_not_found.PutFleetsFleetIdWingsWingIdNotFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
